### ISSUE TITLE
Please support Carthage install

### ISSUE THREAD

**Issue by Natai** [RxSwiftCommunity/RxSegue#8]

**Comment by victorg1991** [comment]
I think this https://github.com/RxSwiftCommunity/RxSegue/pull/7 will solve the problem :)

**Comment by sergdort** [comment]
Hey guys! I've merged #7 thank you very much @victorg1991 👍
I believe it should solve your issue @Natai

**Comment by sergdort** [comment]
I believe we can close this for now
